--------------------------------------------------------------------------------
-- This anonymous block creates a table named MARKETPRICES in
-- schema STOCKAN. PL/SQL Block is restartable, so it can be
-- executed n times, but only creates the table if it does not exist.
--------------------------------------------------------------------------------
BEGIN
  FOR i IN (SELECT 'MARKETPRICES' AS table_name FROM DUAL
            MINUS
            SELECT table_name
              FROM all_tables
             WHERE table_name = 'MARKETPRICES'
               AND owner = USER)
  LOOP
    EXECUTE IMMEDIATE q'{
  CREATE TABLE "MARKETPRICES" 
   (	
  "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 1000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  CONSTRAINT "MARKETPRICES_NN01" NOT NULL ENABLE,
  "SYMBOL_ID" NUMBER CONSTRAINT "MARKETPRICES_NN02" NOT NULL ENABLE,
  "DATE" DATE CONSTRAINT "MARKETPRICES_NN03" NOT NULL ENABLE,
  "OPEN" NUMBER CONSTRAINT "MARKETPRICES_NN04" NOT NULL ENABLE,
  "HIGH" NUMBER CONSTRAINT "MARKETPRICES_NN05" NOT NULL ENABLE,
  "LOW" NUMBER CONSTRAINT "MARKETPRICES_NN06" NOT NULL ENABLE,
  "CLOSE" NUMBER CONSTRAINT "MARKETPRICES_NN07" NOT NULL ENABLE,
  "ADJUSTED_CLOSE" NUMBER CONSTRAINT "MARKETPRICES_NN08" NOT NULL ENABLE,
  "VOLUME" NUMBER CONSTRAINT "MARKETPRICES_NN09" NOT NULL ENABLE,  
  "CREATION_USR" VARCHAR2(64 CHAR) CONSTRAINT "MARKETPRICES_NN10" NOT NULL ENABLE,
  "CREATION_DT" DATE CONSTRAINT "MARKETPRICES_NN11" NOT NULL ENABLE,
  "MODIFICATION_USR" VARCHAR2(64 CHAR),
  "MODIFICATION_DT" DATE,
	 CONSTRAINT "MARKETPRICES_PK" PRIMARY KEY ("SYMBOL_ID","ID")
  USING INDEX LOCAL ENABLE,
  CONSTRAINT "MARKETPRICES_FK" FOREIGN KEY ("SYMBOL_ID") REFERENCES SYMBOLS("ID")
  ENABLE,
  CONSTRAINT "MARKETPRICES_UK" UNIQUE ("SYMBOL_ID", "DATE") USING INDEX LOCAL ENABLE
   ) PARTITION BY LIST("SYMBOL_ID")
  AUTOMATIC(PARTITION p_symbol_id_000001 VALUES (1))
                        }';
  END LOOP;
END;
/

--------------------------------------------------------------------------------
-- Table and column comments of MARKETPRICES
--------------------------------------------------------------------------------
-- no comments defined for MARKETPRICES

--------------------------------------------------------------------------------
-- This is an example of adding a new column, you can just
-- copy and paste the code and adjust it for new columns
--------------------------------------------------------------------------------
BEGIN
  FOR i IN (SELECT 'ID' AS column_name FROM DUAL
            MINUS
            SELECT column_name
              FROM all_tab_cols
             WHERE table_name = 'MARKETPRICES'
               AND column_name = 'ID'
               AND owner = USER)
  LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE MARKETPRICES ADD ' || i.column_name || ' NUMBER';
  END LOOP;
END;
/