--------------------------------------------------------------------------------
-- This anonymous block creates a table named RELATIONS in
-- schema STOCKAN. PL/SQL Block is restartable, so it can be
-- executed n times, but only creates the table if it does not exist.
--------------------------------------------------------------------------------
BEGIN
  FOR i IN (SELECT 'RELATIONS' AS table_name FROM DUAL
            MINUS
            SELECT table_name
              FROM all_tables
             WHERE table_name = 'RELATIONS'
               AND owner = USER)
  LOOP
    EXECUTE IMMEDIATE q'{
  CREATE TABLE "RELATIONS" 
   (	
  "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 1000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  CONSTRAINT "RELATIONS_NN01" NOT NULL ENABLE,
  "RELATION_TYPE_ID" NUMBER CONSTRAINT "RELATIONS_NN02" NOT NULL ENABLE,
  "ID1" NUMBER CONSTRAINT "RELATIONS_NN03" NOT NULL ENABLE,
  "ID2" NUMBER CONSTRAINT "RELATIONS_NN04" NOT NULL ENABLE,
  "CREATION_USR" VARCHAR2(64 CHAR) CONSTRAINT "RELATIONS_NN05" NOT NULL ENABLE,
  "CREATION_DT" DATE CONSTRAINT "RELATIONS_NN06" NOT NULL ENABLE,
  "MODIFICATION_USR" VARCHAR2(64 CHAR),
  "MODIFICATION_DT" DATE,
  CONSTRAINT "RELATIONS_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE,
  CONSTRAINT "RELATIONS_FK" FOREIGN KEY ("RELATION_TYPE_ID") REFERENCES RELATION_TYPES("ID") ENABLE
   )
                        }';
  END LOOP;
END;
/

--------------------------------------------------------------------------------
-- Table and column comments of RELATIONS
--------------------------------------------------------------------------------
-- no comments defined for RELATIONS

--------------------------------------------------------------------------------
-- This is an example of adding a new column, you can just
-- copy and paste the code and adjust it for new columns
--------------------------------------------------------------------------------
BEGIN
  FOR i IN (SELECT 'ID' AS column_name FROM DUAL
            MINUS
            SELECT column_name
              FROM all_tab_cols
             WHERE table_name = 'RELATIONS'
               AND column_name = 'ID'
               AND owner = USER)
  LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE RELATIONS ADD ' || i.column_name || ' NUMBER';
  END LOOP;
END;
/