. get-yahoo-quotes.sh ADS.DE ./STOCKS_DAX30/ADS.DE.csv
. get-yahoo-quotes.sh ALV.DE ./STOCKS_DAX30/ALV.DE.csv
. get-yahoo-quotes.sh BAS.DE ./STOCKS_DAX30/BAS.DE.csv
. get-yahoo-quotes.sh BAYN.DE ./STOCKS_DAX30/BAYN.DE.csv
. get-yahoo-quotes.sh BEI.DE ./STOCKS_DAX30/BEI.DE.csv
. get-yahoo-quotes.sh BMW.DE ./STOCKS_DAX30/BMW.DE.csv
. get-yahoo-quotes.sh CON.DE ./STOCKS_DAX30/CON.DE.csv
. get-yahoo-quotes.sh 1COV.DE ./STOCKS_DAX30/COV.DE.csv
. get-yahoo-quotes.sh DAI.DE ./STOCKS_DAX30/DAI.DE.csv
. get-yahoo-quotes.sh DBK.DE ./STOCKS_DAX30/DBK.DE.csv
. get-yahoo-quotes.sh DB1.DE ./STOCKS_DAX30/DB1.DE.csv
. get-yahoo-quotes.sh DPW.DE ./STOCKS_DAX30/DPW.DE.csv
. get-yahoo-quotes.sh DTE.DE ./STOCKS_DAX30/DTE.DE.csv
. get-yahoo-quotes.sh EOAN.DE ./STOCKS_DAX30/EOAN.DE.csv
. get-yahoo-quotes.sh FRE.DE ./STOCKS_DAX30/FRE.DE.csv
. get-yahoo-quotes.sh FME.DE ./STOCKS_DAX30/FME.DE.csv
. get-yahoo-quotes.sh HEI.DE ./STOCKS_DAX30/HEI.DE.csv
. get-yahoo-quotes.sh HEN3.DE ./STOCKS_DAX30/HEN3.DE.csv
. get-yahoo-quotes.sh IFX.DE ./STOCKS_DAX30/IFX.DE.csv
. get-yahoo-quotes.sh LIN.DE ./STOCKS_DAX30/LIN.DE.csv
. get-yahoo-quotes.sh LHA.DE ./STOCKS_DAX30/LHA.DE.csv
. get-yahoo-quotes.sh MRK.DE ./STOCKS_DAX30/MRK.DE.csv
. get-yahoo-quotes.sh MTX.F ./STOCKS_DAX30/MTX.DE.csv
. get-yahoo-quotes.sh MUV2.DE ./STOCKS_DAX30/MUV2.DE.csv
. get-yahoo-quotes.sh RWE.DE ./STOCKS_DAX30/RWE.DE.csv
. get-yahoo-quotes.sh SAP.DE ./STOCKS_DAX30/SAP.DE.csv
. get-yahoo-quotes.sh SIE.DE ./STOCKS_DAX30/SIE.DE.csv
. get-yahoo-quotes.sh VOW3.DE ./STOCKS_DAX30/VOW3.DE.csv
. get-yahoo-quotes.sh VNA.DE ./STOCKS_DAX30/VNA.DE.csv
. get-yahoo-quotes.sh WDI.DE ./STOCKS_DAX30/WDI.DE.csv
