. get-yahoo-quotes.sh XLP ./ETF/XLP_Consumer_Staples.csv
. get-yahoo-quotes.sh XLV ./ETF/XLV_Health_Care.csv
. get-yahoo-quotes.sh XLC ./ETF/XLC_Communication.csv
. get-yahoo-quotes.sh XLK ./ETF/XLK_Technology.csv
. get-yahoo-quotes.sh SPY ./ETF/SPY_Spyder.csv
. get-yahoo-quotes.sh XLU ./ETF/XLU_Utilities.csv
. get-yahoo-quotes.sh XLB ./ETF/XLB_Materials.csv
. get-yahoo-quotes.sh XLY ./ETF/XLY_Consumer_Discretionary.csv
. get-yahoo-quotes.sh XLRE ./ETF/XLRE_Real_Estate.csv
. get-yahoo-quotes.sh XLI ./ETF/XLI_Industrial.csv
. get-yahoo-quotes.sh XLF ./ETF/XLF_Financial.csv
. get-yahoo-quotes.sh XLE ./ETF/XLE_Energy.csv